### ISSUE TITLE
Searching on datetime field

### ISSUE THREAD

**Issue by illing2005** [pivotal-energy-solutions/django-datatable-view#106]
Beside other fields I have a `DateTimeField` in my datatable.
If I enter digits in the search field I get this error:
   
    ValueError at /history/
    year=122 is before 1900; the datetime strftime() methods require year >= 1900 

Is this a known problem? How can I fix this?
If there is no workaround, how can I exclude this field from searching?

**Comment by tiliv** [comment]
I'd double check that you've got the latest release (5-6 weeks ago or so), which offers a setting variable with a default value that traps values smaller than 1900 (which is when a numerical value is wrongly being tried as a datetime year parameter).

You shouldn't need to do anything to the setting value in the latest release; it'll fix this for you simply by having the code that checks against its default value.

**Comment by illing2005** [comment]
Thanks! That helps
