### ISSUE TITLE
Is it no support 'models fields IPAddressField'?

### ISSUE THREAD

**Issue by boylegu** [pivotal-energy-solutions/django-datatable-view#111]
```
ValueError at /assets/data/
Unhandled field type for xxxx (<class 'django.db.models.fields.IPAddressField'>) in search. 
```

**Comment by tiliv** [comment]
We're about to release a pretty big update where this is no longer a problem, but you can fix this now by adding ``IPAddressField`` as a text-type field:

```python
from datatableview.utils import FIELD_TYPES
FIELD_TYPES['text'].append(models.IPAddressField)
```

You can include this code in one of your project files, and during an ajax query, the view will correctly find the field.

**Comment by boylegu** [comment]
perfect !~ Thank you
