### ISSUE TITLE
Multitable in a view - How to identify a table in template

### ISSUE THREAD

**Issue by benrob42** [pivotal-energy-solutions/django-datatable-view#128]
I have 2 tables in a view.
I would like to select one line from the second table and to copy it to the first table.

I presume i have to remove {{datatable}} and {{datatable_second}} and
create a table id=xxx
but how i will keep the link with get_context_data ?

The code below displayed correctly the 2 tables.

``` javascript
// Page javascript
datatableview.auto_initialize = false;
$(function(){
    var xeditable_options = {};
    datatableview.initialize($('.datatable'), {
        fnRowCallback: datatableview.make_xeditable(xeditable_options),
    });
})
```

...
{{datatable}}
{{datatable_second}}
...

**Comment by tiliv** [comment]
The scope of this question kind of gets away from what either datatableview or even datatables.js can answer.  I think the implementation would require you to attach events to rows in ``datatable_second`` that changes data on the server.  When you reload both tables, the row would appear to move.

If you're trying to do manipulate data only locally, you might have trouble with the tables being backed by server-side data, which is what this package focuses on.
