### ISSUE TITLE
Had a troubles with searching with escaping '\' char

### ISSUE THREAD

**Issue by maximzxc** [pivotal-energy-solutions/django-datatable-view#134]
When using [this thing](https://datatables.net/examples/api/multi_filter_select.html) for searching I noticed that some search request that contains ``'\'`` char not working, for example, searching value ``'C1.1'`` caused problems because in GET response its value was converted to ``'C1\.1'`` .

Changing https://github.com/pivotal-energy-solutions/django-datatable-view/blob/master/datatableview/datatables.py#L484 to 
`return column.search(self.model, terms.replace('\\', ''))` solved my problem, probably it may help someone.

**Comment by tiliv** [comment]
Hm, I feel like I need to reproduce this for myself before I make the change.  I'm fairly sure that nothing in datatableview bothers escaping characters, so blindly replacing the backslashes seems risky.  I'll look at this soon.
