### ISSUE TITLE
New column format is not DRY

### ISSUE THREAD

**Issue by doganmeh** [pivotal-energy-solutions/django-datatable-view#139]
Going through the code, I realized this column format is deprecated:

    class MyDatatable(Datatable):
        class Meta:
            columns = [
                ("ID", 'id', helpers.link_to_model),
                ("Blog", 'blog__name', helpers.link_to_model(key=lambda instance: instance.blog)),
                ("Headline", 'headline', helpers.make_xeditable),
                ("Body Text", 'body_text', helpers.itemgetter(slice(0, 30))),
                ("Publication Date", 'pub_date', helpers.format_date('%A, %b %d, %Y')),
                ("Modified Date", 'mod_date'),
                ("Age", 'pub_date', helpers.through_filter(timesince)),
                ("Interaction", 'get_interaction_total', helpers.make_boolean_checkmark),
                ("Comments", 'n_comments', helpers.format("{0:,}")),
                ("Pingbacks", 'n_pingbacks', helpers.format("{0:,}")),
            ]

in favor of:

    class MyDatatable(Datatable):
        class Meta:
            columns = ['id', 'blog_name', 'headline', 'body_text', 'pub_date', 'mod_date', 'age',
                       'interaction', 'n_comments', 'n_pingbacks']
            processors = {
                'id': helpers.link_to_model,
                'blog_name': helpers.link_to_model(key=lambda obj: obj.blog),
                'headline': helpers.make_xeditable,
                'body_text': helpers.itemgetter(slice(0, 30)),
                'pub_date': helpers.format_date('%A, %b %d, %Y'),
                'n_comments': helpers.format("{0:,}"),
                'n_pingbacks': helpers.format("{0:,}"),
            }

I like the older format better not only because it is more DRY (you don't have to repeat field names here and there, but also you have all the settings for a field in one place, which makes code easier to read. 

It is also possible to have all settings of a column/field in one place by explicitly defining it in the form of: `blog_name = columns.TextColumn(...` but that is verbose.

**Comment by tiliv** [comment]
In this situation, I opted to follow the django Forms strategy, which I agree can be repetitive in cases like this.  Also, the old format ultimately made the declaration of virtualized columns more awkward than I wanted.  For example, I know the difference between the following, but who else does:
* ``("My Column", 'get_my_value')``
* ``("My Column", None, 'get_my_value')``

Also, it was annoying in my experience to declare a field with a processor callback where I didn't want to copy-paste the verbose name from the model into the config list.  The following was not valid:
* ``(None, 'blog_name', 'my_processor')``

So the new column "field" syntax was made, as you mention at the end.  At that point, it felt redundant to support so many different ways of doing something, which is usually not the python way, particularly when I felt the old syntax was so lacking.

At this point I'm fond of the imitation of ``django.forms``, and I don't know if there's a compromise available anymore.

**Comment by doganmeh** [comment]
It is usually good to do what others do :) (although I don't like django's syntax either, if you had a lot of fields, it would become a puzzle to read; esp. if the code was not organized well)
