### ISSUE TITLE
Datatable pageLength option ignored

### ISSUE THREAD

**Issue by paolodina** [pivotal-energy-solutions/django-datatable-view#143]
I noted that Datatable's [`pageLength`](https://datatables.net/reference/option/pageLength) option is ignored when specified in javascript initialization. This is the init code.

```
$(document).ready(function() {
    datatableview.auto_initialize = false;
    datatableview.initialize($('.datatable'), {
        'pageLength': 10 // Ignored, always shows 25 results
    });
});
```
Even if pageLength is `10` it always shows 25 results, and the generated markup reflects this as well:
```
<table data-page-length="25"  role="grid" aria-describedby="DataTables_Table_0_info">
...
</table>
```

It works if I configure the page length via configuration object in Python, but I wonder if this is the expected behavior or if I'm doing something wrong.
```
class MyDataTable(Datatable):
    class Meta:
        model = Article
        page_length = 10 // Works
```

**Comment by doganmeh** [comment]
because as of now master uses old parameter scheme where it was iDisplayLength. Try that one. I have pull request that will fix this, waiting for @tiliv's attention :)
