### ISSUE TITLE
Paging does not work

### ISSUE THREAD

**Issue by doganmeh** [pivotal-energy-solutions/django-datatable-view#148]
Paging does not work. It did not work on my example_app before last night merges either. I could  not verify with live demo on appspot because no datatable over there have more than 1 page. 

I suspect it is because of the new parameter scheme. 1.10 parameters, paging come as follows:

{ ...
'length': ['2'],
'start': ['4'],
... }

**Comment by doganmeh** [comment]
One more thing:
From the [datatables parameter conversion chart](https://datatables.net/upgrade/1.10-convert):
     `iDisplayStart -> displayStart: Initial paging start point`

That seems to be for initial setup only. and datatableview makes no reference to the 'start' I mentioned in the original post. It is not on the conversion chart either. weird.

**Comment by doganmeh** [comment]
Can this be tagged "bug" as well? And, it might need priority over most other issues here, since it is one of the most basic features of the datatable.

**Comment by doganmeh** [comment]
See #157

**Comment by jangeador** [comment]
I am not sure that the paging problem has to deal with the parameters name. In my working branch I still have the names `iDisplayStart` and `iDisplayLength` and paging works with the latest version of Datatables.

In my latest project I tried going back to the official master branch from @tiliv and paging was not working. I then switched to @doganmeh working branch and it was still not working. It turns out that the problem with the paging was that in this particular instance I was using a _proxy model_ as the `model` for the `DataTableview`. As soon as I switched to the regular model paging started working, so I am wondering if the paging problem is related to using proxy models and not the parameter names.

**Comment by doganmeh** [comment]
@jangeador when you switched to regular modal where still on doganmeh or tiliv/master? when I fixed the parameters it did not work for a few times, and then worked (probably after fresh loading of the page or resetting of the local storage cache)

**Comment by jangeador** [comment]
@doganmeh I stand corrected. I must've been using a cached version. I can now confirm that the fixes on your branch work with regular models as well as with proxy models. Thanks for those fixes and thanks for that helper you added.

**Comment by doganmeh** [comment]
I could not find its reference on the datatables.net site, but it is not recommended to mix and match old and new parameters. Once you use some of old parameters, it triggers logic to expect other parameters also same kind.

**Comment by doganmeh** [comment]
Perfect :)

**Comment by sanfirat** [comment]
Bu problemi ben de yasiyorum. kesin bir cozumu var mi @doganmeh

**Comment by doganmeh** [comment]
@sanfirat check out my working branch it should work. 

translation: benim repo'nun 'working' dalini dene, calismasi lazim.

**Comment by sanfirat** [comment]
Thanks... your branch worked.

**Comment by doganmeh** [comment]
@tiliv if you pull 2nd commit in #157, that would fix this issue.. fyi. 

By the way, I am looking forward to version 1.0 (where you clean old configuration). I would like to take a more thorough look at the code, but as it is now, it is a little complicated for me. I am hoping, it will get simpler once the old configuration stuff removed. Regards,

**Comment by devictr** [comment]
Hey !
Sorry I am late to the party but I ran into some issues with the pagination at work. We pulled your pull-request @doganmeh and it broke our non-paginated datatable views. Please see the comment I put here https://github.com/pivotal-energy-solutions/django-datatable-view/pull/157/files

Cheers

**Comment by tiliv** [comment]
Resolved via #171 and #170
