### ISSUE TITLE
Ajax call blows up when searched 'true' or 'false' on a Datatable including a BooleanColumn

### ISSUE THREAD

**Issue by doganmeh** [pivotal-energy-solutions/django-datatable-view#150]
This issue recurred. Related issue #141, pr #142.  See example ChoiceFieldsDatatableView.

**Comment by tiliv** [comment]
This appears to be working in that particular demo.  I did add a column to the Entry demo model that needs to be migrated.  Is it possible that we're confusing it with a db/fixture issue?  I'll need some view into what you see if it's still happening on master.

**Comment by doganmeh** [comment]
I tested it on upstream/master and had deleted the db file, re-migrated and re-installed the fixtures.. I believe it installed the modern one. But I will check again.

**Comment by doganmeh** [comment]
If you revamped the example app as you said you planned, and deploy somewhere, that would help test things against a common setup.

**Comment by doganmeh** [comment]
I really want to include this app in my project, but am not sure because of the glitches with the basics.. Let me know if I can help.

**Comment by tiliv** [comment]
1f4d7d definitely took care of the "string or bytes expected" in the default case (the new line 291), so I'll need to build an example from #141 and investigate again.

**Comment by doganmeh** [comment]
What django version you develop in and manually test? that might be it.. I am on 1.9.x

**Comment by tiliv** [comment]
Hm.  1.9.10 seems to be good for me

**Comment by doganmeh** [comment]
I tried 1.8.x, 1.9, and finally 1.9.10. Tests run fine, but when I search I get this ajax response. I plan on creating a test case that fails:

    Traceback:  
    
    File "/home/virtualenv/datatableview/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
      149.                     response = self.process_exception_by_middleware(e, request)
    
    File "/home/virtualenv/datatableview/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
      147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
    
    File "/home/virtualenv/datatableview/lib/python3.5/site-packages/django/views/generic/base.py" in view
      68.             return self.dispatch(request, *args, **kwargs)
    
    File "/home/virtualenv/datatableview/lib/python3.5/site-packages/django/views/generic/base.py" in dispatch
      88.         return handler(request, *args, **kwargs)
    
    File "/home/github/django-datatable-view/datatableview/views/base.py" in get
      25.             return self.get_ajax(request, *args, **kwargs)
    
    File "/home/github/django-datatable-view/datatableview/views/base.py" in get_ajax
      80.         response_data = self.get_json_response_object(datatable)
    
    File "/home/github/django-datatable-view/datatableview/views/base.py" in get_json_response_object
      42.         datatable.populate_records()
    
    File "/home/github/django-datatable-view/datatableview/datatables.py" in populate_records
      435.         objects = self.search(objects)
    
    File "/home/github/django-datatable-view/datatableview/datatables.py" in search
      463.                 q = search_f(column, term)
    
    File "/home/github/django-datatable-view/datatableview/datatables.py" in _search_column
      477.         return column.search(self.model, terms)
    
    File "/home/github/django-datatable-view/datatableview/columns.py" in search
      370.                     coerced_term = handler.prep_search_value(term, lookup_type)
    
    File "/home/github/django-datatable-view/datatableview/columns.py" in prep_search_value
      496.         return super(BooleanColumn, self).prep_search_value(term, lookup_type)
    
    File "/home/github/django-datatable-view/datatableview/columns.py" in prep_search_value
      293.                 in_bits = re.split(r',\s*', term)
    
    File "/home/virtualenv/datatableview/lib/python3.5/re.py" in split
      203.     return _compile(pattern, flags).split(string, maxsplit)
    
    Exception Type: TypeError at /choices-fields/
    Exception Value: expected string or bytes-like object
    Request information:
    GET:
    columns[4][data] = '4'
    length = '25'
    columns[3][search][value] = ''
    search[regex] = 'false'
    columns[3][orderable] = 'true'
    columns[2][search][regex] = 'false'
    _ = '1475701606971'
    columns[4][searchable] = 'true'
    columns[1][name] = 'headline'
    columns[0][orderable] = 'true'
    columns[0][search][regex] = 'false'
    columns[1][data] = '1'
    columns[1][search][value] = ''
    columns[4][name] = 'is-published'
    columns[2][search][value] = ''
    draw = '5'
    columns[0][name] = 'id'
    columns[2][searchable] = 'true'
    columns[2][orderable] = 'true'
    columns[4][orderable] = 'true'
    columns[0][search][value] = ''
    columns[2][data] = '2'
    search[value] = 'True'
    columns[4][search][regex] = 'false'
    columns[2][name] = 'status-value'
    columns[3][data] = '3'
    columns[4][search][value] = ''
    columns[1][searchable] = 'true'
    columns[3][searchable] = 'true'
    columns[0][data] = '0'
    columns[0][searchable] = 'true'
    start = '0'
    columns[3][search][regex] = 'false'
    columns[1][search][regex] = 'false'
    columns[1][orderable] = 'true'
    columns[3][name] = 'status-display'
    
    POST: No POST data
    
    FILES: No FILES data

**Comment by tiliv** [comment]
Almost exactly as you posted this, I came across something odd, and I'm extremely confused how I made the typo and yet found the error to disappear.  I seem to have been testing the wrong method variable.

Perhaps I've got something weird with my db backend over here that was hiding the error.
