### ISSUE TITLE
Pass extra data from client to the server

### ISSUE THREAD

**Issue by paolodina** [pivotal-energy-solutions/django-datatable-view#153]
I need to pass extra data from client to the server view. In plain datatable plugin I used to initialize the datatable passing this option:

```
'ajax': {
    'url': '/api/endpoint/new',
    'data': function(d) {
        d.name = 'Joe';
}
```

Now if I use the same syntax but with `datatableview` I get an error:

```
datatableview.auto_initialize = false;
datatableview.initialize($('.datatable'), {
'ajax': { // Error
    'url': '/api/endpoint/api',
    'data': function(d) {
      d.name = 'Joe';
    }
},
// 'ajax': '/api/endpoint/new', <-- works fine
```

The error is:

```
DataTables warning: table id=DataTables_Table_0 - Ajax error.
For more information about this error, please see http://datatables.net/tn/7
```

Firebug:

```
"NetworkError: 404 Not Found - http://127.0.0.1:8000/api/endpoint/[object%20Object]?
sEcho=1&iColumns=2&sColumns=codice%2Cdescrizione&iDisplayStart=0&iDisplayLength=10&
mDataProp_0=0&sSearch_0=&bRegex_0=false&bSearchable_0=true&bSortable_0=true&
mDataProp_1=1&sSearch_1=&bRegex_1=false&bSearchable_1=true&bSortable_1=true&sSearch=&
bRegex=false&iSortingCols=0&hey=Joe&_=1475762591663"
```

Please note the part `http://127.0.0.1:8000/api/endpoint/[object%20Object]`.

I'm using datatable view at this commit: b10292c9be43aae26675d64e4e51bde01b9155cf. What did I do wrong?

**Comment by paolodina** [comment]
Followup. I found that [preXhr event](https://datatables.net/reference/event/preXhr) can be used to inject data before the Ajax request to the server.
```
datatableview.initialize($('.datatable')
    .on('preXhr.dt', function(e, settings, data) {
        data.foobar = 'baz';
    });
);
```
I still wonder if it's a the correct way to do that or not, but works.

**Comment by doganmeh** [comment]
Regarding the first comment: for the code at that commit, that name of that parameter is ""sAjaxSource" instead of "ajax", but that also get overriden by what datatableview puts in. In other words, it does not seem possible to override it. See line 106 at https://github.com/pivotal-energy-solutions/django-datatable-view/blob/b10292c9be43aae26675d64e4e51bde01b9155cf/datatableview/static/js/datatableview.js

**Comment by tiliv** [comment]
In the current version, there are two ways you can accomplish this, depending on where it is more useful to hook into the datatableview code.

``datatableview.defaultDataTableOptions`` is an object which is extended on a per-object basis with the select and options object provided to ``datatableview.initialize()``, so you can add a callback like this directly to the default set:

```javascript
// The 'ajax' entry in this object does not exist yet, but if you supply a partial set of options
// like I do below, it will be extended later when the init code wants to add in the url, etc.
//
// Be aware that you're modifying the default options for all tables that initialize on this page!
// Also, be sure you're doing this after the datatableview.js has been included, but before any
// datatables are initialized (e.g., probably don't want to put this in document.onReady)
datatableview.defaultDataTableOptions.ajax = {
    data: function(d){
        d.name = 'Joe';
        return d;
    }
};
```

Alternatively, and if you need per-table controls, you can provide a ``datatableview.finalizeOptions(datatable, options)`` callback, which is called after ``datatableview.initialize()`` is completely done setting up the built-in options from the template-rendered table.  You can inspect the table object to make sure you changing the right one, etc.

```javascript
$(function(){
    datatableview.finalizeOptions = function(datatable, options){
        // options.ajax is already fully formed in this scenario.
        options.ajax.data = function(d){
            d.name = 'Joe';
        };
        return options;  // Always return the options
    };
```
