### ISSUE TITLE
Some helpers don't work on LegacyDatatableView

### ISSUE THREAD

**Issue by doganmeh** [pivotal-energy-solutions/django-datatable-view#155]
Because default_value don't go into the kwargs. Example code:

```
def get_bool_check_mark(object, **kwargs):
    if kwargs.get('default_value', None):
        return '<span class="text-success">&#10004;</span>'
    else:
        return '<span class="text-danger">&#10008;</span>'


class LegacyPersonDatatableView(LegacyDatatableView):
    model = Person
    template_name = "school/persons_grid_dt.html"
    datatable_options = {
        'columns': ['id',
                    ('username', modal_link_to_model),
                    'first_name',
                    'last_name',
                    'email',
                    'school',
                    ('is_active', get_bool_check_mark),
                    ('is_pending', get_bool_check_mark),
                    ('is_staff', get_bool_check_mark),
                    ('is_school_contact', get_bool_check_mark),
                    'actions']
    }
    structure_template = "datatableview/bootstrap_structure.html"
```

Here modal_link_to_model works but not the get_bool_check_mark.

**Comment by tiliv** [comment]
I think what's going on in the code you've posted is that the helper function is actually being provided as if it was the data source, which doesn't receive any special arguments.  Calling a callable in that second position is something that was added in 35d21d9 during our recent merges.  I think it risks confusion like this, but I see the value of providing callbacks (not helpers).

To correctly specify a processor callback, it must be the third argument in the tuple, which means that you are compelled to provide a verbose name in the first position:

```python
("Active", 'is_active', get_bool_check_mark)
```

It's one of the several reasons why the legacy syntax was a pain to work with :(

**Comment by doganmeh** [comment]
I see. If you plan on supporting old syntax longer, and if it is worth the trouble, it can be required that the processor be provided only as a callable, so you know when it is string, it is the field name.

**Comment by doganmeh** [comment]
You can close this if you like..
