### ISSUE TITLE
Regex Searching

### ISSUE THREAD

**Issue by jangeador** [pivotal-energy-solutions/django-datatable-view#156]
Is there a setting that will allow me to use regex in my searches?

**Comment by tiliv** [comment]
For the moment we're missing a ``Datatable.Meta`` option to specify which columns can use regex (like you can with verbose names and processors, etc), but when constructing a column instance you can pass the ``allow_regex=True`` kwarg:

```python
content = columns.TextField(source='content', allow_regex=True)
```

What this does is add ``__iregex`` to the lookups tried on the field during the filter step.

**Comment by jangeador** [comment]
That is awesome, and that will work fine for me as I declare most of my columns in this fashion.
