### ISSUE TITLE
Keyed helpers

### ISSUE THREAD

**Issue by doganmeh** [pivotal-energy-solutions/django-datatable-view#166]
https://github.com/pivotal-energy-solutions/django-datatable-view/blob/master/datatableview/helpers.py#L90:

    If the helper is called in place (rather than providing the helper reference directly), it can
    receive a special ``key`` argument, which is a mapping function that will receiving the instance
    (once it is available) and return some value from that instance.  That new value will be sent to
    the helper in the place of the instance.
    Examples::
        # Generate a simple href tag for instance.get_absolute_url()
        name = columns.TextColumn("Name", sources=['name'],
                                          processor=link_to_model)
        # Generate an href tag for instance.relatedobject.get_absolute_url()
        # Note that without the use of link_to_model(key=...), the object going into
        # the link_to_model helper would be the row instance, not the thing looked up by the
        # column's sources.
        name = columns.TextColumn("Name", sources=['relatedobject__name'],
                                          processor=link_to_model(key=getattr('relatedobject')))

Keyed helpers are nice in that, it enables use of generic helpers with arbitrarily related objects (ORM paths) of a given object. However, that also makes me think, why would the `relatedobject` in the above example NOT put in the helper as `the instance` in the first place?

Here is the thing that made me question this. I have noticed there is a lot of repetition in my use of processors: link_to_model for all ForeignKeys, get_boolean_checkmark for all booleans etc. I am imagining a feature which enables assignment (through django settings maybe) of default processors to model fields. Implementation of that would be much easier if most helpers could be used with the default instance put in the helper (without needing attribute getters).

**Comment by tiliv** [comment]
Essentially, the issue is that the ``sources`` list could have anything in it, including a combination of multiple related objects.

That said, I know the syntax is pretty crufty.  I'm looking at changing this helper to allow something like this in the field kwargs:

```python
# Link to base object instance
link_to_model('self')

# Link to arbitrary related object
link_to_model('relatedobject')
```

**Comment by tiliv** [comment]
Making a reference to #157 .  I think adapting this helper will be more graceful than adding a second one dedicated to related objects.
