### ISSUE TITLE
Footer=True overwrites custom css styling

### ISSUE THREAD

**Issue by kvdogan** [pivotal-energy-solutions/django-datatable-view#173]
Hi,

When I set footer=True for 'per column searching' in a table has more than 5 columns, all of the custom css styling I make for width of columns are getting overwritten and I can not change it. I do not know if it is a bug.

thanks in advance

**Comment by kvdogan** [comment]
ok, it's fixed by adding following code in the template, just for the record.

tfoot input {
    width: 100%;
    padding: 3px;
    box-sizing: border-box;
}

**Comment by jangeador** [comment]
Can you please share an example with per-column-search?

**Comment by kvdogan** [comment]
I use following as datatable initialization for per column search and it works fine.

`<script type="text/javascript">

    datatableview.auto_initialize = false;
    $(function(){
        var common_options = {
          "bStateSave": true,
          "scrollCollapse": true,
          "pagingType": "full_numbers",
          "dom": "Brltip",
          "columnDefs": [
              {"className": "dt-center", "targets": [3,4,9,10,11]}
            ],
        };
        var datatable = datatableview.initialize($('.datatable'), common_options);
        // Per Column search text input initialization
        $('.datatable tfoot th').each(function(){
            var title = $('.datatable thead th').eq($(this).index()).text();
            $(this).html('<input type="text" placeholder='+title+'>');
        });
        // Per column search initialization
        var table = datatable.api();
        table.columns().every(function(){
            var column = this;
            $('input', column.footer()).on('keyup change', function(){
                if (column.search() !== this.value) {
                    column.search(this.value).draw();
                }
            });
            // Custom buttom functions for resetting column search, 
            $("#reset-columns").click( function(){
                   column.search('').draw();
                   $('input').val('');
                 });
        });
    });


  </script>`
