### ISSUE TITLE
is `attrgetter` helper obsolete?

### ISSUE THREAD

**Issue by doganmeh** [pivotal-energy-solutions/django-datatable-view#180]
With the advance of `attr` argument for the keyed helpers, there does not seem to be much use case left for the `attrgetter` helper. 

In its docstring below example is given however `get_address` could be called as a processor itself, if given as a string literal. 

```
address = columns.TextColumn("Address", sources=['street', 'city', 'state', 'zip'],
                                     processor=attrgetter('get_address'))
```

On another note, it can traverse paths that contain `callables` in addition to what you can do with the `attr` argument, however, that does not seem to be a common use case.

**Comment by tiliv** [comment]
> ``get_address`` could be called as a processor itself, if given as a string literal.

Potentially, but a processor needs to take ``**kwargs``, and the target of ``attrgetter`` does not, because ``attrgetter``` consumes those arguments to prevent errors.
