### ISSUE TITLE
Please release a new version compatible with Django 1.10

### ISSUE THREAD

**Issue by utapyngo** [pivotal-energy-solutions/django-datatable-view#184]
The latest PyPI version is 0.8.3 which is incompatible with Django 1.10

**Comment by tiliv** [comment]
Yeah, sorry about that.  We're getting the 0.9/1.0 stuff on master cleaned up for proper release.  Using master should work better, although it's part of the API redesign, so check the readme for links to the new documentation and included example project.

**Comment by PamelaM** [comment]
Is there a timeline for this?  It would be incredibly helpful if this could get done sooner rather than later.

**Comment by rh0dium** [comment]
Hey Pamela - We will get in out this coming week - We are also moving to it ;)

**Comment by PamelaM** [comment]
Great, then we'll do development off of the 0.9/beta branch!

**Comment by PamelaM** [comment]
👉  (poke) Any news for 0.9 release to pypi?

**Comment by tiliv** [comment]
I'll be fixing documentation and closing a few outstanding items and then we should be in the clear!

**Comment by PamelaM** [comment]
Thanks

**Comment by tiliv** [comment]
Busy week last week, but we'll have this available as soon as possible.

**Comment by gridranger** [comment]
Thank you for your work. :+1:  I am looking forward to this fix. :)

**Comment by pvandriessche** [comment]
do you have any news on this fix? 
Appreciate the work!

**Comment by azreda** [comment]
Meanwhile, if you'd like to remain on the 0.8X release, and would like compatibility with Django 1.10/1.11, here is a fork with compatibility updates: https://github.com/azreda/django-datatable-view

**Comment by utapyngo** [comment]
@azreda  is it released to PyPI?

**Comment by azreda** [comment]
@utapyngo no PyPI plans. Just a set of workarounds until an official solution.

**Comment by utapyngo** [comment]
Won't you mind if I release it to PyPI?

**Comment by azreda** [comment]
@utapyngo I don't think that's a good idea because it'll be confusing with this project, and gives the illusion of support. I think interested people can find it on this thread, and let's have the regular contributors chime on their plans for Django 1.10+ support first.

**Comment by utapyngo** [comment]
I am not a django-datatable-view developer, so I can't and did not mean to release it as `django-datatable-view`. I meant another name, say, `django-datatable-view-compat`.

**Comment by tiliv** [comment]
@utapyngo Is directly installing the @azreda mirror repo not sufficient?  I assumed you avoided installing our ``master`` branch due to the new syntaxes and wanted 0.8 with Django 1.10 fixes, but it sounds like your primary concern is having it on PyPI.  Of course, we definitely intend to have our 1.0 released there soon, but installing directly from a github URL is a useful stopgap until the PyPI release happens.

**Comment by utapyngo** [comment]
@tiliv pip caching does not seem to work well with repos, so I want to install all dependencies from PyPI.

**Comment by tiliv** [comment]
@utapyngo That's an unfortunate problem to have for how useful the feature is.  I'm not sure what would cause that.

I tend to agree with @azreda concerning the publishing of a repo that will never be updated—I'd probably be more keen on fixing whatever's wrong with pip than resorting to publishing a stopgap repo.  That said, I suppose there are plenty of orphaned one-off packages on PyPI.

We'll get our release out soon, but be warned that it will require porting a few bits of code to use it once it lands.

**Comment by utapyngo** [comment]
@tiliv  The problem is that pip must clone the repo anew for every install, ignoring the default download cache entirely.
https://stackoverflow.com/questions/28158192/caching-remote-repository-for-pip-installs

**Comment by tiliv** [comment]
@utapyngo Hm.  Well, when we release to PyPI, it goes to github and grabs the install payload there.  We don't host anything on PyPI, so it sounds like the difference would be "cloning" versus fetching the payload.  Using the ``-e`` option in pip when targetting a repo would make it do a real clone, but omitting it I believe just installs it to your ``env/src/`` folder in essentially the same way as a PyPI install.

**Comment by utapyngo** [comment]
@azreda  you repo is based on 0.8.2.
Could you merge 0.8.3?

**Comment by todorvelichkov** [comment]
@tiliv any updates on 1.0? Is Django 1.11 supporter with the current github version (0.9.0-beta.6) or we should use the forked one from @azreda

**Comment by Suor** [comment]
Any updates?

**Comment by utapyngo** [comment]
@Suor: I have uploaded @azreda's version to https://pypi.python.org/pypi/django-datatable-view-compat/0.8.2

The upcoming 0.8.3 version will be compatible with Django 2.0 (sources here: https://github.com/utapyngo/django-datatable-view/tree/django20)

**Comment by Suor** [comment]
@utapyngo thanks
