### ISSUE TITLE
Do you have plan to support python 3

### ISSUE THREAD

**Issue by xayangjing** [pivotal-energy-solutions/django-datatable-view#190]
Hi Sir,

This tools is very cool and usefull.
Do you have any plan to support python3 ?

**Comment by tiliv** [comment]
We have Python 3 ready on the master branch, approaching release very soon.  The last few weeks have required nonstop attention elsewhere.  It's a major release, so you'll want to be familiar with the new documentation linked on the README.

Thanks for your interest!
