### ISSUE TITLE
exmaple  site is not working 

### ISSUE THREAD

**Issue by xayangjing** [pivotal-energy-solutions/django-datatable-view#191]
Hi Sir,

When I try some demo tables but it  is not working now.
It always report as belw:
DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

http://django-datatable-view.appspot.com/

**Comment by tiliv** [comment]
For reference, the appspot site was stuck using a fork of django to support appengine's db environment.  Google has changed things and provided tools to get newer django (and Python 2.7!) to work, but that demo site is for pre 0.9/1.0.  When I finally push the release out, we'll have a non-appengine site running.

The new site is packaged in ``datatableview.tests.example_project`` and can be run locally in the mean time (see main repo README for the quick no-config setup—it's basically just a migrate+loaddata for the sqlite file, and then runserver)
