### ISSUE TITLE
Keeping checked rows throw the pages

### ISSUE THREAD

**Issue by mauroka** [pivotal-energy-solutions/django-datatable-view#202]
Hello, is there a way to keep the checked row when navigating throw the pages? It's because I would like to keep the selections or get the selections in all the pages, not just the current one?
Is that possible?
Thanks a lot.

**Comment by tiliv** [comment]
Not within the scope of what this project is supplying.  I'm unfamiliar with official ways to handle that, but if there is one from datatables.js, we would be happy to accommodate!
