### ISSUE TITLE
How do I use CompoundColumn in latest version?

### ISSUE THREAD

**Issue by GvS666** [pivotal-energy-solutions/django-datatable-view#203]
I tried using it like in the example here: http://django-datatable-view.appspot.com/virtual-column-definitions/

but it's not working.

**Comment by jangeador** [comment]
Here is an example using the new definition:
```py3
    class datatable_class(Datatable):
        blog = columns.TextColumn("Blog", sources=['blog__name'])
        age = columns.TextColumn("Age", sources=None, processor='get_entry_age')

        class Meta:
            columns = ['blog', 'headline', 'age']

        def get_entry_age(self, instance, **kwargs):
            return timesince(instance.pub_date)
```

source:
https://github.com/pivotal-energy-solutions/django-datatable-view/blob/cd0e22f090a772a915a991297b550fb68d869221/datatableview/tests/example_project/example_project/example_app/views.py#L421

**Comment by GvS666** [comment]
Thank you!
