### ISSUE TITLE
Unhandled field type (psfields.JSON)

### ISSUE THREAD

**Issue by pedrovgp** [pivotal-energy-solutions/django-datatable-view#210]
I am trying to use DatatableView for a model with a json field and am receiving this Exception. I am on master. I looked for FIELD_TYPES in utils, but since the LegacyMode was dropped, it does not seem to exist. Are there ways to avoid this exception, ideally by registering the new field type but, alternativelly, by ignoring it?

**Comment by jangeador** [comment]
What exception is that?

**Comment by pedrovgp** [comment]
Well, I want to build a list view for one of my models. I am using class based view, inheriting from ConfigureDatatableObjectDatatableView, which inherits DatatableView. When I access the view's URL, I get this exception specifically: Unhandled model field <django.contrib.postgres.fields.jsonb.JSONField: json>.

The tracebak leads to 

> datatableview/datatables.py in columns_for_model


 ```
            column_class = get_column_for_modelfield(f)`

            if column_class is None:

                raise ColumnError("Unhandled model field %r." % (f,)) 

            if labels and f.name in labels:

                label = labels[f.name]
```
The third line above is line 53 in the file. There is where the exception is raised.

My model contains a postgresql specific field, which is the [JSONfield](https://docs.djangoproject.com/en/2.0/ref/contrib/postgres/fields/#django.contrib.postgres.fields.JSONField).

**Comment by jangeador** [comment]
Ok, I see. I have used json fields before and they work. The problem is that you are trying to let the automatic system determine your column. You probably don't want to fetch the field contents that way because the results would be in json format. 

The way I have done it is not to include the json field in the meta columns and just use a custom method to extract the data. Here is an example:

```py3
class AssessmentDetailTable(Datatable):
    observed_growth = columns.TextColumn(processor='get_observed_growth')
    expected_growth = columns.TextColumn(processor='get_expected_growth')
    difference = columns.TextColumn(processor='get_difference')

    def get_observed_growth(self, instance, *args, **kwargs):
        return instance.results['observed_growth']

    def get_expected_growth(self, instance, *args, **kwargs):
        return instance.results['expected_growth']

    def get_difference(self, instance, *args, **kwargs):
        return '{}'.format(float(instance.results['difference']))

    class Meta:
        columns = ['student']
```

In the above code, the data for the columns `observed_growth`, `expected_growth`, and `difference` all comes from a `JSONField` called `results`

**Comment by pedrovgp** [comment]
Thank you very much, that worked :)
