### ISSUE TITLE
Unhandled model field:TimeField

### ISSUE THREAD

**Issue by mezitax** [pivotal-energy-solutions/django-datatable-view#216]
I have an error

> datatableview.exceptions.ColumnError: Unhandled model field <django.db.models.fields.TimeField: time>.

in my models:
```
class Retreat(models.Model):
    time = models.TimeField(editable=True)
```
I think it's because TimeField is not registered in the column list
https://github.com/pivotal-energy-solutions/django-datatable-view/blob/master/docs/datatableview/columns.rst
Is there any way to register TimeField in the django-datatable-view columns?

**Comment by mezitax** [comment]
this works for me
adding this line to columns.py:
```
class TimeColumn(Column):
    model_field_class = models.TimeField
    handles_field_classes = [models.TimeField]
    lookups_types = ('exact', 'in', 'range', 'hour', 'minute', 'second')
```
django 2.0 and python 3.6

**Comment by tiliv** [comment]
This should work by having it anywhere on your imported modules, btw. It will self-register to the model field. I’ll get TimeField added soon. My apologies.

**Comment by mezitax** [comment]
I just created a new columns.py inside my project until this improvement is in the official version
Thank you

**Comment by tiliv** [comment]
Added to latest!
