### ISSUE TITLE
a time wasting mistake in README.md

### ISSUE THREAD

**Issue by karimabdelhakim** [pivotal-energy-solutions/django-datatable-view#229]
`datatableview.initialize('.datatable');` -> `datatableview.initialize($('.datatable'));`

**Comment by alshar** [comment]
Thank you so much for posting this. I was trying to figure out for about an hour why this wasn't working. 
DataTable loads fine after I used this.

**Comment by jnoortheen** [comment]
@karimabdelhakim As the readme is updated now, this can be closed.
