### ISSUE TITLE
pypi updates

### ISSUE THREAD

**Issue by kptac** [pivotal-energy-solutions/django-datatable-view#251]
Hello, was wondering if you plan on doing pypi updates any time soon.

Also, would like to thank you all for this project, excellent work. I've been using this on a project, and very happy with the results so far. Right now, I've been testing with 2.1.4 and would love to install it with pip instead of git@ tag. Any particular reason why you're holding it off?

Thanks

**Comment by rh0dium** [comment]
None I'm Lazy.  I'll try and knock this out over the next week or so.

**Comment by rh0dium** [comment]
Done!

**Comment by kptac** [comment]
Doesn't seem to work for me though:

`pip install django-datatable-view==2.1.6
ERROR: Could not find a version that satisfies the requirement django-datatable-view==2.1.6 (from versions: 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.9.0)
ERROR: No matching distribution found for django-datatable-view==2.1.6`
