### ISSUE TITLE
Need a "clean" way to add field types.

### ISSUE THREAD

**Issue by xxinfinityxx** [pivotal-energy-solutions/django-datatable-view#49]
Hi there,

I'm using [django-netfields](https://pypi.python.org/pypi/django-netfields) in my app and I while trying to display a table with netfields elements I ran into this:

```
ValueError: Unhandled field type for address (<class 'netfields.fields.InetAddressField'>) in search.
```

So, I looked in the code and so far, the only way I found was to override the "quite big" apply_queryset_options in the DatatableMixin class.

Could it be possible to have a more _user friendly_ way to add more supported types ? Perhaps making this "if options['search']:" a separate function definition that could be used with _super()_.

Any ideas?

**Comment by tiliv** [comment]
I'll treat this as closed for now on account of the closed #53.  Allowing custom queryset language is still of interest to me, which may lead me to reference this field type again in the future.
