### ISSUE TITLE
all the input of the page filter the datatable

### ISSUE THREAD

**Issue by twinsc** [pivotal-energy-solutions/django-datatable-view#52]
I have a page with an input in the side menu, when in the content i load a datatable, the input of the sidemenu search the datatable, it is not near in the html to the datatable. I remove the script for initialization and this strange behavior stop and works as usual.

**Comment by tiliv** [comment]
I realize it's been a while since this was posted, but I'm not sure what may have been going wrong.  If I can get a code example I can look into it further.  My initial attempt to reproduce this didn't work.
