### ISSUE TITLE
Little help on initComplete timing ....

### ISSUE THREAD

**Issue by Youpsla** [pivotal-energy-solutions/django-datatable-view#79]
I try to add dropdown filter for columns.
I've tried to implement the code available here: http://www.datatables.net/examples/api/multi_filter_select.html

Then I've done 2 things.

First one:
```
.......
</body>
        <script type="text/javascript">

        datatableview.auto_initialize = false;
$(document).ready( function () {
$('.datatable').DataTable( {
        initComplete: function () {
            var api = this.api();
......
```
As a result, there is no data in the table.

Second thing:
```
........
</body>
        <script type="text/javascript">

        datatableview.auto_initialize = false;
$(document).ready( function () {
$('.datatable').DataTable( {
    datatableview.initialize(".datatable"));
        initComplete: function () {
            var api = this.api();
.......
```
In this case, datas are in the table but no dropdowns .....

I've read the js initialisation help but I'm not sure if initComplete is run by datatableview before I run it in my code.

Any help would be appreciated.

If this is not the place for help, let me know !!!!

**Comment by tiliv** [comment]
Because the DatatableView need to provide its own configuration details, ``datatableview.initialize(".datatable")`` will actually perform the whole javascript init process, and allows you to pass your mapping of options as the second arg.

We dump some configuration options into the table DOM as ``data-*`` attributes that will be read by `datatableview.initialize()`` to build a starting point of options, and then any additional options supplied by the second arg will trump those:

```javascript
datatableview.auto_initialize = false;
$(document).ready(function(){
    datatableview.initialize($(".datatable"), {
        initComplete: function(){
            var api = this.api();
            // ...
        }
    });
```

So the ``initComplete`` should be sent to our init helper by nature of the fact that it's building the options it intends to send to the real dataTables.js constructor.  You should be able to completely avoid calling the vanilla constructor yourself, as this might produce some unexpected results.

Let me know how the situation changes by trying that.

**Comment by Youpsla** [comment]
Hi tillv,
thanks a lots for your answer and explanations. I understand better the process. Of course it still doesn't work. With the code bellow, no footer is added to the table. I suspect an issue with ```.appendTo( $(column.footer()).empty() )``` in the following code:
```
datatableview.auto_initialize = false;
$(document).ready( function () {
    datatableview.initialize($(".datatable"), {
        initComplete: function(){
            var api = this.api();
            api.columns().indexes().flatten().each( function ( i ) {
                var column = api.column( i );
                var select = $('<select><option value=""></option></select>')
                    .appendTo( $(column.footer()).empty() )
                    .on( 'change', function () {
                        var val = $.fn.dataTable.util.escapeRegex(
                            $(this).val()
                        );
                        column
                            .search( val ? '^'+val+'$' : '', true, false )
                            .draw();
                    } );
                    console.log($('<select><option value=""></option></select>').appendTo( $(column.footer())));
                column.data().unique().sort().each( function ( d, j ) {
                    select.append( '<option value="'+d+'">'+d+'</option>' )
                    console.log(d);
                    console.log(j);
                } );
            } );
        }
    } );
```
All console.log() seems to have accurate informations.

and here is my view where some options are defined.
```
class DataTableView(DatatableView):
    model = Agent 
    template_name = 'client/datatable.html'
    datatable_options = {
        #'structure_template': "datatableview/bootstrap_structure.html",
        'columns': [
            'firstname',
            'lastname',
            ("Certification", 'agent__certifications', 'get_agent_certifications'),
            ("Id", 'get_id'),
        ]
        }

    def get_agent_certifications(self, instance, *args, **kwargs):
        return ", ".join([Certification.long_name for Certification in instance.certifications.all()])
```
Any idea are welcome ....

And another thing, how can you pass an option like ```"paging": false``` in the view. This raise an python error because ```false``` in undefined. With quotes around ```"false"``` there is no error but no effect too !!! lol
