### ISSUE TITLE
Support request: removing an instance from the queryset

### ISSUE THREAD

**Issue by 7wonders** [pivotal-energy-solutions/django-datatable-view#80]
Its been a while since I contributed to datatable-view so I am a bit rusty. 

@tiliv - is there any way that I can remove an instance from the results but from within the column methods or preload? I use get_queryset to get my results and then I do some smaller lookups in the column methods based on the instance. I would like to then remove that row completely if it doesnt meet some specific criteria that cant be found with queryset.

**Comment by tiliv** [comment]
I'm not sure there's a particularly great way to do that right now.  Of course, the original ``get_queryset()`` is the ideal place for this, but I could see how this could come up in a complex situation.

I will add something soon to deal with this.
